import type {
	IAuthenticateGeneric,
	ICredentialDataDecryptedObject,
	ICredentialTestRequest,
	ICredentialType,
	IHttpRequestHelper,
	INodeProperties,
} from 'n8n-workflow';

import {
	INTEGRATION_NOT_INSTALLED,
	INTEGRATION_NOT_INSTALLED_HINT,
} from '../nodes/UnoPim/transport';

const REJECTED =
	'Those credentials were rejected. Copy all four values from the same row under ' +
	'Configuration > Integrations > API Keys. The Username is the generated API username ' +
	'in the form integration+<id>@api.local — not your own admin login.';

export class UnoPimApi implements ICredentialType {
	name = 'unoPimApi';

	displayName = 'UnoPim API';

	icon = 'file:unopim.svg' as const;

	documentationUrl = 'https://docs.unopim.com/';

	properties: INodeProperties[] = [
		{
			displayName: 'UnoPim URL',
			name: 'baseUrl',
			type: 'string',
			default: '',
			placeholder: 'https://demo.unopim.com',
			required: true,
			description: 'Root URL of your UnoPim instance, without a trailing slash',
		},
		{
			displayName: 'Client ID',
			name: 'clientId',
			type: 'string',
			default: '',
			required: true,
			description:
				'From Configuration > Integrations > API Keys in UnoPim. Create a key, then copy its Client ID.',
		},
		{
			displayName: 'Client Secret',
			name: 'clientSecret',
			type: 'string',
			typeOptions: { password: true },
			default: '',
			required: true,
			description: 'The Client Secret on the same row as the Client ID',
		},
		{
			displayName: 'Username',
			name: 'username',
			type: 'string',
			default: '',
			required: true,
			placeholder: 'integration+1@api.local',
			description:
				'The API username on the same row, generated by UnoPim in the form integration+<id>@api.local. This is not your own admin login.',
		},
		{
			displayName: 'Password',
			name: 'password',
			type: 'string',
			typeOptions: { password: true },
			default: '',
			required: true,
			description: 'The API password on the same row, not your own admin password',
		},
		{
			displayName: 'Session Token',
			name: 'sessionToken',
			type: 'hidden',
			typeOptions: { password: true, expirable: true },
			default: '',
		},
	];

	async preAuthentication(
		this: IHttpRequestHelper,
		credentials: ICredentialDataDecryptedObject,
	): Promise<{ sessionToken: string }> {
		const baseUrl = normaliseBaseUrl(credentials.baseUrl as string);

		let response: { access_token?: string };

		try {
			response = (await this.helpers.httpRequest({
				method: 'POST',
				url: `${baseUrl}/oauth/token`,
				headers: {
					Accept: 'application/json',
					'Content-Type': 'application/x-www-form-urlencoded',
				},
				body: new URLSearchParams({
					grant_type: 'password',
					client_id: String(credentials.clientId ?? ''),
					client_secret: String(credentials.clientSecret ?? ''),
					username: String(credentials.username ?? ''),
					password: String(credentials.password ?? ''),
					scope: '',
				}).toString(),
				json: true,
			})) as { access_token?: string };
		} catch {
			throw new Error(REJECTED);
		}

		if (!response?.access_token) {
			throw new Error(
				'UnoPim did not return an access token. Check that the UnoPim URL points at the application root and that /oauth/token is reachable there.',
			);
		}

		return { sessionToken: response.access_token };
	}

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {
			headers: {
				Authorization: '=Bearer {{$credentials.sessionToken}}',
				Accept: 'application/json',
			},
		},
	};

	supportedNodes = ['unoPim', 'unoPimTrigger'];

	test: ICredentialTestRequest = {
		request: {
			baseURL: '={{$credentials.baseUrl.replace(/\\/+$/, "")}}',
			url: '/api/v1/rest/n8n/me',
		},
		rules: [
			{
				type: 'responseCode',
				properties: {
					value: 404,
					message: `${INTEGRATION_NOT_INSTALLED} ${INTEGRATION_NOT_INSTALLED_HINT}`,
				},
			},
		],
	};
}

export function normaliseBaseUrl(baseUrl: string): string {
	const trimmed = (baseUrl ?? '').trim().replace(/\/+$/, '');

	if (!/^https?:\/\//i.test(trimmed)) {
		throw new Error('The UnoPim URL must start with http:// or https://.');
	}

	const url = new URL(trimmed);

	if (url.username || url.password) {
		throw new Error(
			'Remove the username and password from the UnoPim URL. Enter them in the fields below instead.',
		);
	}

	if (url.search || url.hash) {
		throw new Error(
			'The UnoPim URL must not contain a query string or fragment. Use just the address, for example https://demo.unopim.com.',
		);
	}

	if (/\/admin$/i.test(url.pathname)) {
		throw new Error(
			'Remove "/admin" from the end of the UnoPim URL. This field takes the application root, ' +
				`for example ${trimmed.replace(/\/admin$/i, '') || 'https://demo.unopim.com'}, not the admin panel address.`,
		);
	}

	return trimmed;
}
